[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_type = debug            ; 🟢 THÊM DÒNG NÀY: Để khi crash, nó chỉ đích danh dòng code nào bị lỗi
monitor_filters =
    esp32_exception_decoder   ; Giải mã từ khóa crash sang dòng code
    time
monitor_dtr = 1
monitor_rts = 0
upload_port = /dev/cu.usbmodem21201
monitor_port = /dev/cu.usbmodem21201

; --- Cấu hình ép nhận đủ 16MB Flash & 8MB OPI PSRAM cho N16R8 ---
board_build.arduino.memory_type = dio_opi
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; --- Cấu hình flags ---
build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    
    ; --- ÉP PHẲNG CONFIG CỦA LVGL ---
    -D LV_CONF_INCLUDE_SIMPLE
    -I src/
    
    ; --- CẤU HÌNH DRIVER MÀN HÌNH TFT_eSPI THẲNG TỪ INI ---
    -D USER_SETUP_LOADED=1
    ; -D ST7789_DRIVER=1
    -D ILI9341_DRIVER=1         ; Cập nhật sang driver ILI9341 cho màn hình RoHS 320x240
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_RGB_ORDER=TFT_RGB    ; Đảo màu nếu màn hình hiển thị ngược màu
    ; Chân SPI: KHỚP với dây cắm vật lý của bạn (13,12,15,4,5)
    ; KHÔNG dùng GPIO 35-39 vì đó là chân OPI PSRAM nội của N16R8!
    -D TFT_MISO=-1
    -D TFT_MOSI=13
    -D TFT_SCLK=12
    -D TFT_CS=15
    -D TFT_DC=4
    -D TFT_RST=5
    -D TFT_BL=2
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=10000000   ; 10MHz - ổn định nhất cho dây jumper dài

lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    lvgl/lvgl @ 8.3.11
    bodmer/TFT_eSPI @ ^2.5.43



